export const nodes = [
  { id: "lu-177", name: "Lu-177", type: "Isotope", val: 10 },
  { id: "mo-99", name: "Mo-99 / Tc-99m", type: "Isotope", val: 9 },
  { id: "ac-225", name: "Ac-225", type: "Isotope", val: 8 },
  { id: "si-28", name: "Si-28", type: "Isotope", val: 9 },
  { id: "he-3", name: "He-3", type: "Isotope", val: 7 },
  { id: "li-6", name: "Li-6", type: "Isotope", val: 10 },
  { id: "li-7", name: "Li-7", type: "Isotope", val: 6 },
  { id: "haleu", name: "HALEU", type: "Isotope", val: 8 },
  { id: "gas-centrifugation", name: "Gas centrifugation enrichment", type: "Process", val: 11 },
  { id: "reactor-production", name: "Reactor-based production", type: "Process", val: 10 },
  { id: "accelerator-production", name: "Accelerator production", type: "Process", val: 7 },
  { id: "tritium-breeding", name: "Tritium breeding", type: "Process", val: 8 },
  { id: "haleu-enrichment", name: "HALEU enrichment", type: "Process", val: 8 },
  { id: "precision-medicine", name: "Precision Medicine / Theranostics", type: "Application", val: 14 },
  { id: "quantum-technologies", name: "Quantum Technologies", type: "Application", val: 12 },
  { id: "nuclear-fusion", name: "Nuclear Production / Fusion", type: "Application", val: 13 },
];

export const links = [
  { source: "lu-177", target: "precision-medicine" },
  { source: "lu-177", target: "reactor-production" },
  { source: "lu-177", target: "mo-99" },
  { source: "mo-99", target: "precision-medicine" },
  { source: "mo-99", target: "reactor-production" },
  { source: "ac-225", target: "precision-medicine" },
  { source: "ac-225", target: "accelerator-production" },
  { source: "si-28", target: "quantum-technologies" },
  { source: "si-28", target: "gas-centrifugation" },
  { source: "he-3", target: "quantum-technologies" },
  { source: "li-6", target: "nuclear-fusion" },
  { source: "li-6", target: "gas-centrifugation" },
  { source: "li-6", target: "tritium-breeding" },
  { source: "li-7", target: "nuclear-fusion" },
  { source: "haleu", target: "haleu-enrichment" },
  { source: "gas-centrifugation", target: "si-28" },
  { source: "gas-centrifugation", target: "li-6" },
  { source: "reactor-production", target: "mo-99" },
  { source: "reactor-production", target: "lu-177" },
  { source: "accelerator-production", target: "ac-225" },
  { source: "tritium-breeding", target: "li-6" },
  { source: "precision-medicine", target: "lu-177" },
  { source: "precision-medicine", target: "mo-99" },
  { source: "precision-medicine", target: "ac-225" },
  { source: "quantum-technologies", target: "si-28" },
  { source: "quantum-technologies", target: "he-3" },
  { source: "nuclear-fusion", target: "li-6" },
  { source: "nuclear-fusion", target: "li-7" },
];

export const typeColors = {
  Isotope: "#a78bfa",
  Process: "#60a5fa",
  Application: "#fbbf24",
};
