export const nodes = [
  // ─── Medical / research isotopes ───
  { id: "mo-99", name: "Mo-99 / Tc-99m", type: "Isotope", val: 12, note: "Diagnostic workhorse. Supply depends on a small reactor network. Outage risk is structural." },
  { id: "lu-177", name: "Lu-177", type: "Isotope", val: 11, note: "Therapeutic isotope. Demand is rising faster than easy reactor and processing capacity." },
  { id: "ac-225", name: "Ac-225", type: "Isotope", val: 10, note: "Alpha-emitter for targeted therapy. Scalable production is still the constraint." },
  { id: "pb-212", name: "Pb-212", type: "Isotope", val: 9, note: "Alpha-therapy related isotope in the lead/bismuth decay pathways. Production remains specialized." },
  { id: "ra-223", name: "Ra-223", type: "Isotope", val: 9, note: "Alpha-emitting therapeutic isotope used in targeted treatment pathways." },
  { id: "y-90", name: "Y-90", type: "Isotope", val: 9, note: "Therapeutic isotope used in targeted radiotherapy and selected interventional procedures." },
  { id: "re-188", name: "Re-188", type: "Isotope", val: 8, note: "Therapeutic radioisotope often discussed in generator and targeted therapy contexts." },
  { id: "ga-68", name: "Ga-68", type: "Isotope", val: 9, note: "PET imaging isotope commonly obtained through generator systems fed by Ge-68." },
  { id: "ge-68", name: "Ge-68", type: "Isotope", val: 8, note: "Parent isotope for Ga-68 generators. Specialized production underpins a large share of Ga-68 access." },
  { id: "cu-64", name: "Cu-64", type: "Isotope", val: 8, note: "PET isotope with growing research and clinical interest. Capacity is limited relative to mainstream PET nuclides." },
  { id: "zr-89", name: "Zr-89", type: "Isotope", val: 8, note: "Longer-lived PET isotope used in research and antibody imaging workflows." },
  { id: "c-11", name: "C-11", type: "Isotope", val: 8, note: "Short-lived PET isotope produced on cyclotrons close to imaging sites." },
  { id: "xe-133", name: "Xe-133", type: "Isotope", val: 7, note: "Noble-gas radioisotope used in selected diagnostic applications." },
  { id: "tb-161", name: "Tb-161", type: "Isotope", val: 8, note: "Emerging therapeutic isotope. Production pathways are still scaling." },
  { id: "i-131", name: "I-131", type: "Isotope", val: 10, note: "Therapeutic and diagnostic radioiodine with long-standing reactor-based supply routes." },
  { id: "f-18", name: "F-18", type: "Isotope", val: 10, note: "PET imaging isotope. Short-lived supply depends on cyclotron networks." },
  { id: "co-60", name: "Co-60", type: "Isotope", val: 9, note: "Industrial and medical radioisotope used in sterilization, processing, and selected therapy contexts." },
  { id: "ir-192", name: "Ir-192", type: "Isotope", val: 8, note: "Industrial and brachytherapy radioisotope. Supply is specialized and facility-dependent." },

  // ─── Stable / specialty isotopes ───
  { id: "si-28", name: "Si-28", type: "Isotope", val: 10, note: "Enriched silicon for quantum materials. Limited by separation capacity." },
  { id: "o-18", name: "O-18", type: "Isotope", val: 9, note: "Stable isotope feedstock used to produce F-18. Critical upstream input for PET supply." },
  { id: "c-13", name: "C-13", type: "Isotope", val: 8, note: "Stable carbon isotope used in research, labeling, and selected industrial applications." },
  { id: "n-15", name: "N-15", type: "Isotope", val: 8, note: "Stable nitrogen isotope used in research and tracer applications." },
  { id: "b-10", name: "B-10", type: "Isotope", val: 9, note: "Neutron-absorbing boron isotope important in nuclear control materials and selected medical pathways." },
  { id: "he-3", name: "He-3", type: "Isotope", val: 10, note: "Scarce helium isotope. Practical supply has mainly come from tritium decay recovery, not bulk helium production." },
  { id: "li-6", name: "Li-6", type: "Isotope", val: 11, note: "Fusion-relevant lithium isotope. Enriched from natural lithium; feeds tritium breeding." },
  { id: "li-7", name: "Li-7", type: "Isotope", val: 7, note: "Complement to Li-6 in nuclear chemistry and related systems." },
  { id: "haleu", name: "HALEU", type: "Isotope", val: 10, note: "High-assay low-enriched uranium product. Depends on scarce enrichment above LEU." },
  { id: "h-2", name: "H-2 Deuterium", type: "Isotope", val: 8, note: "Heavy hydrogen for research, moderators, and fusion-related use." },
  { id: "h-3", name: "H-3 Tritium", type: "Isotope", val: 9, note: "Fusion fuel isotope linked to Li-6 breeding pathways and He-3 recovery." },

  // ─── Processes ───
  { id: "reactor-production", name: "Reactor production", type: "Process", val: 13, note: "Neutron-based isotope creation. Backbone of medical isotope supply." },
  { id: "accelerator-production", name: "Accelerator production", type: "Process", val: 10, note: "Charged-particle routes for medical and research isotopes." },
  { id: "cyclotron-production", name: "Cyclotron production", type: "Process", val: 9, note: "Local accelerator route for short-lived medical isotopes such as F-18." },
  { id: "radiochemical-processing", name: "Radiochemical processing", type: "Process", val: 10, note: "Separation, purification, and product preparation between irradiation and usable isotope products." },
  { id: "gas-centrifugation", name: "Gas centrifugation", type: "Process", val: 13, note: "Industrial isotope separation by mass. Core enrichment method." },
  { id: "laser-enrichment", name: "Laser enrichment", type: "Process", val: 9, note: "Optical isotope separation pathway for selected uranium and specialty isotope applications." },
  { id: "haleu-enrichment", name: "HALEU enrichment", type: "Process", val: 9, note: "Enrichment pathway toward HALEU product. Capacity is limited." },
  { id: "tritium-breeding", name: "Tritium breeding", type: "Process", val: 9, note: "Converts Li-6 pathways into tritium for fusion fuel concepts." },
  { id: "he3-recovery", name: "Tritium decay recovery", type: "Process", val: 9, note: "Helium-3 recovered as tritium decays and is processed." },
  { id: "uranium-conversion", name: "Uranium conversion", type: "Process", val: 10, note: "Converts uranium concentrates into UF6 feedstock for enrichment plants." },

  // ─── Applications ───
  { id: "precision-medicine", name: "Precision Medicine", type: "Application", val: 14, note: "Imaging and targeted radiotherapy that depend on isotope supply." },
  { id: "quantum-technologies", name: "Quantum Technologies", type: "Application", val: 12, note: "Needs ultra-pure or rare isotopes such as Si-28 and He-3." },
  { id: "nuclear-fusion", name: "Nuclear / Fusion", type: "Application", val: 13, note: "Depends on enriched materials, breeding routes, and nuclear infrastructure." },
  { id: "industrial-uses", name: "Industrial Uses", type: "Application", val: 11, note: "Sterilization, radiography, tracers, and other industrial applications that depend on selected radioisotopes and stable isotopes." },

  // ─── Reactor facilities ───
  { id: "hfir", name: "HFIR", type: "Facility", val: 8, note: "High Flux Isotope Reactor, Oak Ridge. Major U.S. production node." },
  { id: "murr", name: "MURR", type: "Facility", val: 8, note: "Missouri university reactor. Important medical isotope production site." },
  { id: "atr", name: "ATR", type: "Facility", val: 7, note: "Advanced Test Reactor, Idaho. High-power irradiation capability." },
  { id: "mcmaster", name: "McMaster", type: "Facility", val: 7, note: "Canadian university reactor with isotope production activity." },
  { id: "br2", name: "BR2", type: "Facility", val: 7, note: "Belgian research reactor. Major European isotope production node." },
  { id: "hfr-petten", name: "HFR Petten", type: "Facility", val: 7, note: "Netherlands research reactor. Key medical isotope supply node." },
  { id: "frm-ii", name: "FRM II", type: "Facility", val: 7, note: "German research reactor supporting neutron research and isotope-related work." },
  { id: "ill", name: "ILL", type: "Facility", val: 6, note: "Institut Laue-Langevin neutron source in Grenoble." },
  { id: "lvr-15", name: "LVR-15", type: "Facility", val: 6, note: "Czech research reactor supporting irradiation and isotope-related work." },
  { id: "opal", name: "OPAL", type: "Facility", val: 7, note: "Australian research reactor supporting radioisotope production." },
  { id: "hanaro", name: "HANARO", type: "Facility", val: 6, note: "South Korean research reactor with irradiation capability." },
  { id: "dhruva", name: "Dhruva", type: "Facility", val: 6, note: "Indian research reactor node with isotope production relevance." },
  { id: "carr", name: "CARR", type: "Facility", val: 6, note: "Chinese advanced research reactor node." },
  { id: "jrr-3", name: "JRR-3", type: "Facility", val: 6, note: "Japanese research reactor supporting neutron and isotope-related work." },
  { id: "safari-1", name: "SAFARI-1", type: "Facility", val: 7, note: "Pelindaba research reactor. Key African isotope production node." },
  { id: "riar", name: "RIAR", type: "Facility", val: 7, note: "Dimitrovgrad complex. Major Russian isotope production node." },
  { id: "maria", name: "MARIA", type: "Facility", val: 6, note: "Polish research reactor contributing to isotope production capacity." },
  { id: "ra-3", name: "RA-3", type: "Facility", val: 6, note: "Argentine research reactor supporting regional isotope production." },
  { id: "etrr-2", name: "ETRR-2", type: "Facility", val: 6, note: "Egyptian research reactor node." },
  { id: "iea-r1", name: "IEA-R1", type: "Facility", val: 6, note: "Brazilian research reactor supporting research and isotope-related activity." },

  // ─── Accelerators ───
  { id: "blip", name: "BLIP", type: "Facility", val: 7, note: "Brookhaven accelerator isotope production node." },
  { id: "triumf", name: "TRIUMF", type: "Facility", val: 7, note: "Canadian accelerator centre with isotope production capability." },
  { id: "lanl-ipf", name: "LANL IPF", type: "Facility", val: 6, note: "Los Alamos Isotope Production Facility." },
  { id: "arronax", name: "ARRONAX", type: "Facility", val: 6, note: "French accelerator facility focused on medical radioisotope production." },
  { id: "psi", name: "PSI", type: "Facility", val: 6, note: "Paul Scherrer Institute. Swiss accelerator-based isotope node." },
  { id: "ithemba", name: "iThemba LABS", type: "Facility", val: 6, note: "South African accelerator facility with isotope production capability." },

  // ─── Enrichment / conversion / recovery ───
  { id: "centrus-piketon", name: "Centrus ACP", type: "Facility", val: 8, note: "Piketon enrichment site. Advanced enrichment and HALEU pathway." },
  { id: "urenco-usa", name: "Urenco USA", type: "Facility", val: 8, note: "Eunice, New Mexico commercial uranium enrichment plant." },
  { id: "urenco-almelo", name: "Urenco Netherlands", type: "Facility", val: 7, note: "Almelo enrichment plant." },
  { id: "urenco-uk", name: "Urenco UK", type: "Facility", val: 7, note: "Capenhurst enrichment plant." },
  { id: "urenco-de", name: "Urenco Deutschland", type: "Facility", val: 7, note: "Gronau enrichment plant." },
  { id: "orano-tricastin", name: "Orano GBII", type: "Facility", val: 8, note: "Georges Besse II at Tricastin." },
  { id: "novouralsk", name: "Novouralsk UEIP", type: "Facility", val: 7, note: "Russian commercial enrichment site." },
  { id: "zelenogorsk", name: "Zelenogorsk ECP", type: "Facility", val: 7, note: "Russian commercial enrichment site." },
  { id: "seversk", name: "Seversk SCC", type: "Facility", val: 6, note: "Russian enrichment / fuel-cycle site." },
  { id: "angarsk", name: "Angarsk AECC", type: "Facility", val: 6, note: "Russian enrichment site." },
  { id: "lanzhou", name: "Lanzhou Enrichment", type: "Facility", val: 6, note: "Chinese enrichment site." },
  { id: "hanzhong", name: "Hanzhong Enrichment", type: "Facility", val: 6, note: "Chinese enrichment site." },
  { id: "rokkasho", name: "JNFL Rokkasho", type: "Facility", val: 6, note: "Japanese enrichment site." },
  { id: "resende", name: "INB Resende", type: "Facility", val: 6, note: "Brazilian enrichment site." },
  { id: "rattehalli", name: "RMP Rattehalli", type: "Facility", val: 6, note: "Indian enrichment site." },
  { id: "asp-pretoria", name: "ASP Pretoria", type: "Facility", val: 7, note: "Specialty isotope enrichment in Pretoria." },
  { id: "savannah-river", name: "Savannah River Site", type: "Facility", val: 7, note: "DOE site associated with tritium processing pathways relevant to He-3 recovery." },
  { id: "metropolis-conversion", name: "Metropolis conversion", type: "Facility", val: 7, note: "Key U.S. commercial uranium conversion context for UF6 feedstock." },
  { id: "bellwether-lab", name: "Bellwether Lab", type: "Facility", val: 7, note: "TerraPower Isotopes Ac-225 manufacturing project in Philadelphia." },

  // ─── Companies ───
  { id: "urenco", name: "Urenco", type: "Company", val: 8, note: "Major commercial enricher with plants in Europe and the U.S." },
  { id: "centrus", name: "Centrus Energy", type: "Company", val: 7, note: "U.S. enrichment company focused on advanced enrichment and HALEU." },
  { id: "orano", name: "Orano", type: "Company", val: 7, note: "Fuel-cycle company including major commercial enrichment capacity." },
  { id: "asp-isotopes", name: "ASP Isotopes", type: "Company", val: 7, note: "Specialty isotope enrichment company with Pretoria facilities." },
  { id: "silex", name: "Silex", type: "Company", val: 7, note: "Laser enrichment technology company." },
  { id: "framatome", name: "Framatome", type: "Company", val: 7, note: "Nuclear fuel and technology company." },
  { id: "curium", name: "Curium", type: "Company", val: 7, note: "Major radiopharmaceutical company across diagnostic and therapeutic chains." },
  { id: "lantheus", name: "Lantheus", type: "Company", val: 7, note: "Medical imaging and radiopharmaceutical company." },
  { id: "northstar", name: "NorthStar", type: "Company", val: 7, note: "Medical isotope company focused on diagnostic radioisotope pathways including Mo-99." },
  { id: "itm", name: "ITM", type: "Company", val: 7, note: "Radiopharmaceutical company active in therapeutic isotope development and supply." },
  { id: "telix", name: "Telix", type: "Company", val: 7, note: "Radiopharmaceutical company focused on diagnostic and therapeutic nuclear medicine." },
  { id: "novartis", name: "Novartis", type: "Company", val: 7, note: "Pharmaceutical company with radioligand therapy programs." },
  { id: "bayer", name: "Bayer", type: "Company", val: 7, note: "Pharmaceutical company with targeted radionuclide therapy activity." },
  { id: "terrapower-isotopes", name: "TerraPower Isotopes", type: "Company", val: 8, note: "Expanding Ac-225 supply, including a large Philadelphia manufacturing project." },
  { id: "shine", name: "SHINE", type: "Company", val: 7, note: "Medical isotope company developing non-traditional Mo-99 related pathways." },
  { id: "nusano", name: "Nusano", type: "Company", val: 7, note: "Radioisotope production company building medical isotope capacity." },
  { id: "pantera", name: "PanTera", type: "Company", val: 7, note: "Focused on Ac-225 production scale-up." },
  { id: "niowave", name: "Niowave", type: "Company", val: 7, note: "Accelerator-based medical isotope company including Ac-225 related supply." },
  { id: "orano-med", name: "Orano Med", type: "Company", val: 7, note: "Orano nuclear medicine arm focused on targeted alpha therapy." },
  { id: "ire", name: "IRE", type: "Company", val: 7, note: "Belgian radioisotope producer important to Mo-99 supply." },
  { id: "artms", name: "ARTMS", type: "Company", val: 6, note: "Technology company focused on cyclotron-based medical isotope production routes." },
  { id: "isotopia", name: "Isotopia", type: "Company", val: 6, note: "Radiopharmaceutical and isotope company active in therapeutic isotope supply." },
  { id: "sofie", name: "SOFIE", type: "Company", val: 6, note: "Radiopharma company connected to PET manufacturing activity." },
  { id: "bwxt", name: "BWXT", type: "Company", val: 7, note: "Nuclear manufacturer with isotope-related nuclear work." },
  { id: "eckert-ziegler", name: "Eckert & Ziegler", type: "Company", val: 7, note: "Radiopharmaceutical and isotope technology company." },
  { id: "ansto", name: "ANSTO", type: "Company", val: 7, note: "Australian nuclear science organization with OPAL-related radioisotope production." },
  { id: "ntp", name: "NTP", type: "Company", val: 7, note: "South African radioisotope producer linked to SAFARI-1." },
  { id: "iba", name: "IBA", type: "Company", val: 6, note: "Accelerator technology company connected to nuclear medicine infrastructure." },
  { id: "convertdyn", name: "ConverDyn", type: "Company", val: 6, note: "U.S. uranium conversion joint venture context." },
  { id: "doe-isotope-program", name: "DOE Isotope Program", type: "Company", val: 8, note: "U.S. program coordinating isotope production and distribution across national laboratory capabilities." },
];

export const links = [
  // Medical / industrial isotope chains
  { source: "mo-99", target: "reactor-production", relation: "produced_by" },
  { source: "mo-99", target: "precision-medicine", relation: "used_in" },
  { source: "mo-99", target: "radiochemical-processing", relation: "requires" },
  { source: "lu-177", target: "reactor-production", relation: "produced_by" },
  { source: "lu-177", target: "precision-medicine", relation: "used_in" },
  { source: "lu-177", target: "radiochemical-processing", relation: "requires" },
  { source: "ac-225", target: "accelerator-production", relation: "produced_by" },
  { source: "ac-225", target: "precision-medicine", relation: "used_in" },
  { source: "pb-212", target: "precision-medicine", relation: "used_in" },
  { source: "ra-223", target: "precision-medicine", relation: "used_in" },
  { source: "y-90", target: "reactor-production", relation: "produced_by" },
  { source: "y-90", target: "precision-medicine", relation: "used_in" },
  { source: "re-188", target: "precision-medicine", relation: "used_in" },
  { source: "ga-68", target: "precision-medicine", relation: "used_in" },
  { source: "ga-68", target: "ge-68", relation: "requires" },
  { source: "ge-68", target: "accelerator-production", relation: "produced_by" },
  { source: "cu-64", target: "accelerator-production", relation: "produced_by" },
  { source: "cu-64", target: "precision-medicine", relation: "used_in" },
  { source: "zr-89", target: "accelerator-production", relation: "produced_by" },
  { source: "zr-89", target: "precision-medicine", relation: "used_in" },
  { source: "c-11", target: "cyclotron-production", relation: "produced_by" },
  { source: "c-11", target: "precision-medicine", relation: "used_in" },
  { source: "xe-133", target: "reactor-production", relation: "produced_by" },
  { source: "xe-133", target: "precision-medicine", relation: "used_in" },
  { source: "tb-161", target: "reactor-production", relation: "produced_by" },
  { source: "tb-161", target: "precision-medicine", relation: "used_in" },
  { source: "i-131", target: "reactor-production", relation: "produced_by" },
  { source: "i-131", target: "precision-medicine", relation: "used_in" },
  { source: "f-18", target: "cyclotron-production", relation: "produced_by" },
  { source: "f-18", target: "precision-medicine", relation: "used_in" },
  { source: "f-18", target: "o-18", relation: "requires" },
  { source: "co-60", target: "reactor-production", relation: "produced_by" },
  { source: "co-60", target: "industrial-uses", relation: "used_in" },
  { source: "co-60", target: "precision-medicine", relation: "used_in" },
  { source: "ir-192", target: "reactor-production", relation: "produced_by" },
  { source: "ir-192", target: "industrial-uses", relation: "used_in" },
  { source: "ir-192", target: "precision-medicine", relation: "used_in" },

  // Stable specialty
  { source: "si-28", target: "gas-centrifugation", relation: "enriched_by" },
  { source: "si-28", target: "quantum-technologies", relation: "used_in" },
  { source: "o-18", target: "industrial-uses", relation: "used_in" },
  { source: "o-18", target: "precision-medicine", relation: "used_in" },
  { source: "c-13", target: "industrial-uses", relation: "used_in" },
  { source: "n-15", target: "industrial-uses", relation: "used_in" },
  { source: "b-10", target: "nuclear-fusion", relation: "used_in" },
  { source: "b-10", target: "industrial-uses", relation: "used_in" },
  { source: "he-3", target: "quantum-technologies", relation: "used_in" },
  { source: "he-3", target: "he3-recovery", relation: "produced_by" },
  { source: "h-3", target: "he3-recovery", relation: "requires" },
  { source: "he3-recovery", target: "savannah-river", relation: "located_at" },

  // Fusion materials
  { source: "li-6", target: "gas-centrifugation", relation: "enriched_by" },
  { source: "li-6", target: "tritium-breeding", relation: "requires" },
  { source: "li-6", target: "nuclear-fusion", relation: "used_in" },
  { source: "li-7", target: "nuclear-fusion", relation: "used_in" },
  { source: "h-2", target: "nuclear-fusion", relation: "used_in" },
  { source: "h-3", target: "tritium-breeding", relation: "produced_by" },
  { source: "h-3", target: "nuclear-fusion", relation: "used_in" },
  { source: "haleu", target: "haleu-enrichment", relation: "enriched_by" },
  { source: "haleu", target: "nuclear-fusion", relation: "used_in" },
  { source: "haleu", target: "uranium-conversion", relation: "requires" },

  // Reactors
  { source: "reactor-production", target: "hfir", relation: "located_at" },
  { source: "reactor-production", target: "murr", relation: "located_at" },
  { source: "reactor-production", target: "atr", relation: "located_at" },
  { source: "reactor-production", target: "mcmaster", relation: "located_at" },
  { source: "reactor-production", target: "br2", relation: "located_at" },
  { source: "reactor-production", target: "hfr-petten", relation: "located_at" },
  { source: "reactor-production", target: "frm-ii", relation: "located_at" },
  { source: "reactor-production", target: "ill", relation: "located_at" },
  { source: "reactor-production", target: "lvr-15", relation: "located_at" },
  { source: "reactor-production", target: "opal", relation: "located_at" },
  { source: "reactor-production", target: "hanaro", relation: "located_at" },
  { source: "reactor-production", target: "dhruva", relation: "located_at" },
  { source: "reactor-production", target: "carr", relation: "located_at" },
  { source: "reactor-production", target: "jrr-3", relation: "located_at" },
  { source: "reactor-production", target: "safari-1", relation: "located_at" },
  { source: "reactor-production", target: "riar", relation: "located_at" },
  { source: "reactor-production", target: "maria", relation: "located_at" },
  { source: "reactor-production", target: "ra-3", relation: "located_at" },
  { source: "reactor-production", target: "etrr-2", relation: "located_at" },
  { source: "reactor-production", target: "iea-r1", relation: "located_at" },

  // Accelerators
  { source: "accelerator-production", target: "blip", relation: "located_at" },
  { source: "accelerator-production", target: "triumf", relation: "located_at" },
  { source: "accelerator-production", target: "lanl-ipf", relation: "located_at" },
  { source: "accelerator-production", target: "arronax", relation: "located_at" },
  { source: "accelerator-production", target: "psi", relation: "located_at" },
  { source: "accelerator-production", target: "ithemba", relation: "located_at" },

  // Enrichment / conversion sites
  { source: "gas-centrifugation", target: "centrus-piketon", relation: "located_at" },
  { source: "gas-centrifugation", target: "urenco-usa", relation: "located_at" },
  { source: "gas-centrifugation", target: "urenco-almelo", relation: "located_at" },
  { source: "gas-centrifugation", target: "urenco-uk", relation: "located_at" },
  { source: "gas-centrifugation", target: "urenco-de", relation: "located_at" },
  { source: "gas-centrifugation", target: "orano-tricastin", relation: "located_at" },
  { source: "gas-centrifugation", target: "novouralsk", relation: "located_at" },
  { source: "gas-centrifugation", target: "zelenogorsk", relation: "located_at" },
  { source: "gas-centrifugation", target: "seversk", relation: "located_at" },
  { source: "gas-centrifugation", target: "angarsk", relation: "located_at" },
  { source: "gas-centrifugation", target: "lanzhou", relation: "located_at" },
  { source: "gas-centrifugation", target: "hanzhong", relation: "located_at" },
  { source: "gas-centrifugation", target: "rokkasho", relation: "located_at" },
  { source: "gas-centrifugation", target: "resende", relation: "located_at" },
  { source: "gas-centrifugation", target: "rattehalli", relation: "located_at" },
  { source: "gas-centrifugation", target: "asp-pretoria", relation: "located_at" },
  { source: "haleu-enrichment", target: "centrus-piketon", relation: "located_at" },
  { source: "uranium-conversion", target: "metropolis-conversion", relation: "located_at" },
  { source: "uranium-conversion", target: "gas-centrifugation", relation: "supplies" },
  { source: "silex", target: "laser-enrichment", relation: "supplies" },
  { source: "laser-enrichment", target: "haleu-enrichment", relation: "related_to" },

  // Companies
  { source: "centrus", target: "centrus-piketon", relation: "operates" },
  { source: "centrus", target: "haleu-enrichment", relation: "supplies" },
  { source: "urenco", target: "urenco-usa", relation: "operates" },
  { source: "urenco", target: "urenco-almelo", relation: "operates" },
  { source: "urenco", target: "urenco-uk", relation: "operates" },
  { source: "urenco", target: "urenco-de", relation: "operates" },
  { source: "urenco", target: "gas-centrifugation", relation: "supplies" },
  { source: "orano", target: "orano-tricastin", relation: "operates" },
  { source: "orano", target: "gas-centrifugation", relation: "supplies" },
  { source: "asp-isotopes", target: "asp-pretoria", relation: "operates" },
  { source: "asp-isotopes", target: "si-28", relation: "supplies" },
  { source: "framatome", target: "haleu", relation: "supplies" },
  { source: "framatome", target: "nuclear-fusion", relation: "supplies" },
  { source: "convertdyn", target: "metropolis-conversion", relation: "operates" },
  { source: "convertdyn", target: "uranium-conversion", relation: "supplies" },
  { source: "curium", target: "precision-medicine", relation: "supplies" },
  { source: "curium", target: "mo-99", relation: "supplies" },
  { source: "curium", target: "lu-177", relation: "supplies" },
  { source: "lantheus", target: "precision-medicine", relation: "supplies" },
  { source: "lantheus", target: "f-18", relation: "supplies" },
  { source: "northstar", target: "mo-99", relation: "supplies" },
  { source: "northstar", target: "reactor-production", relation: "supplies" },
  { source: "itm", target: "precision-medicine", relation: "supplies" },
  { source: "itm", target: "lu-177", relation: "supplies" },
  { source: "telix", target: "precision-medicine", relation: "supplies" },
  { source: "telix", target: "lu-177", relation: "supplies" },
  { source: "novartis", target: "precision-medicine", relation: "supplies" },
  { source: "novartis", target: "lu-177", relation: "supplies" },
  { source: "bayer", target: "precision-medicine", relation: "supplies" },
  { source: "bayer", target: "ac-225", relation: "supplies" },
  { source: "bayer", target: "ra-223", relation: "supplies" },
  { source: "terrapower-isotopes", target: "ac-225", relation: "supplies" },
  { source: "terrapower-isotopes", target: "precision-medicine", relation: "supplies" },
  { source: "terrapower-isotopes", target: "bellwether-lab", relation: "operates" },
  { source: "shine", target: "mo-99", relation: "supplies" },
  { source: "shine", target: "precision-medicine", relation: "supplies" },
  { source: "nusano", target: "precision-medicine", relation: "supplies" },
  { source: "nusano", target: "accelerator-production", relation: "supplies" },
  { source: "pantera", target: "ac-225", relation: "supplies" },
  { source: "pantera", target: "precision-medicine", relation: "supplies" },
  { source: "niowave", target: "ac-225", relation: "supplies" },
  { source: "niowave", target: "accelerator-production", relation: "supplies" },
  { source: "orano-med", target: "precision-medicine", relation: "supplies" },
  { source: "orano-med", target: "pb-212", relation: "supplies" },
  { source: "ire", target: "mo-99", relation: "supplies" },
  { source: "ire", target: "precision-medicine", relation: "supplies" },
  { source: "artms", target: "cyclotron-production", relation: "supplies" },
  { source: "artms", target: "mo-99", relation: "related_to" },
  { source: "isotopia", target: "lu-177", relation: "supplies" },
  { source: "isotopia", target: "precision-medicine", relation: "supplies" },
  { source: "sofie", target: "f-18", relation: "supplies" },
  { source: "sofie", target: "precision-medicine", relation: "supplies" },
  { source: "bwxt", target: "reactor-production", relation: "supplies" },
  { source: "bwxt", target: "precision-medicine", relation: "supplies" },
  { source: "eckert-ziegler", target: "precision-medicine", relation: "supplies" },
  { source: "eckert-ziegler", target: "lu-177", relation: "supplies" },
  { source: "ansto", target: "opal", relation: "operates" },
  { source: "ansto", target: "mo-99", relation: "supplies" },
  { source: "ansto", target: "precision-medicine", relation: "supplies" },
  { source: "ntp", target: "safari-1", relation: "related_to" },
  { source: "ntp", target: "mo-99", relation: "supplies" },
  { source: "ntp", target: "precision-medicine", relation: "supplies" },
  { source: "iba", target: "cyclotron-production", relation: "supplies" },
  { source: "iba", target: "precision-medicine", relation: "related_to" },
  { source: "doe-isotope-program", target: "hfir", relation: "related_to" },
  { source: "doe-isotope-program", target: "blip", relation: "related_to" },
  { source: "doe-isotope-program", target: "lanl-ipf", relation: "related_to" },
  { source: "doe-isotope-program", target: "precision-medicine", relation: "supplies" },
];

export const typeColors = {
  Isotope: "#a78bfa",
  Process: "#60a5fa",
  Application: "#fbbf24",
  Facility: "#34d399",
  Company: "#f472b6",
};

export const typeList = [
  "Isotope",
  "Process",
  "Application",
  "Facility",
  "Company",
];
